// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8pjd9f6cb3GPyx7WAyiOahVCHPG2qYNY',
    appId: '1:567607274224:web:0ed06c8444989a2634f035',
    messagingSenderId: '567607274224',
    projectId: 'notify-eve',
    authDomain: 'notify-eve.firebaseapp.com',
    storageBucket: 'notify-eve.firebasestorage.app',
    measurementId: 'G-Q5TVNKXSLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSeW7TfBPujOlthtDB4JHy3OLM9YbRH7Y',
    appId: '1:567607274224:android:a0891578cb76333c34f035',
    messagingSenderId: '567607274224',
    projectId: 'notify-eve',
    storageBucket: 'notify-eve.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8N1cstUNZthzH7oneSWxTXFupxMK-MWM',
    appId: '1:567607274224:ios:ecb980caada2d24234f035',
    messagingSenderId: '567607274224',
    projectId: 'notify-eve',
    storageBucket: 'notify-eve.firebasestorage.app',
    iosBundleId: 'com.example.notifyEvent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8N1cstUNZthzH7oneSWxTXFupxMK-MWM',
    appId: '1:567607274224:ios:ecb980caada2d24234f035',
    messagingSenderId: '567607274224',
    projectId: 'notify-eve',
    storageBucket: 'notify-eve.firebasestorage.app',
    iosBundleId: 'com.example.notifyEvent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8pjd9f6cb3GPyx7WAyiOahVCHPG2qYNY',
    appId: '1:567607274224:web:ddf0f5058cfad95a34f035',
    messagingSenderId: '567607274224',
    projectId: 'notify-eve',
    authDomain: 'notify-eve.firebaseapp.com',
    storageBucket: 'notify-eve.firebasestorage.app',
    measurementId: 'G-1RD8RSLT9K',
  );
}
